language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    secure: kVc4AgC6au2VMC5+V3gm2CTEf6CUaCzD/Sh3UqO9QQGy/12q6px6/JSuTRR9ue061Tqe6ZsMs8wGLhotOGUocVROeM+oLbBReKMiorL5Oj3XfjbVoefpLNdiEWqn5pq2RAJhopidPb45JstxRL3nEap1gjVWC1DHsZ5S0oButcTXv1RKGsjJVjBs0rseMOKEjX0qwhzckAd2PZ8da12jtSo5gILsYoIHJg48BTuRq5qeOC1NR+fcknokrkfI5tdGt1oQ3lT2LDH02UiWLtVkoGVkc0GPacCNtZTkkYGFcDanGeup7REU85iSEqb4kDhnb2BVd2rzlKuJVcvynjUGr/N/P5Wv3UIu710yONFsW+0CcIRPQ9e5+agrcPaeGwVY2GshEt+qhr3eKhm91l8uI7rLRj7xInR1myrcAPTOhTurc0gqTG0j24r6L6rsBTyfuHiCFl+B9ejWfAGqlTPnLKCTLfzAnkWw6cJXkqx95b7BN/CYgl/SOulyzdbfQwLcrPq/rcUdLmxVpv9oD/4huwU4Prz4/B69zpec/TRbmT4na+7WdXdp9sMDt9vE1YQZgLwzPRr6+XrKdJUHbuHdcE3CmG5d+yf4aSftfCLE79EYpYenpYD43i7Z5QmpHsBlDmsGYQ7ZLGhGcXWmo61I91OGXdxheQBgDqUeNNO7B/Q=
script:
- yarn build
deploy:
  provider: s3
  skip_cleanup: true
  local_dir: build
  access_key_id: AKIAIT2VUESRMN64QKWA
  secret_access_key:
    secure: XuNTiTpAq0NJyLl+zTuiPbr/4h0p6ceQpLkvO7cHAHlZOheIny9Iy1ZRbW2MqQHi7XhDTUXVtJ+nAgOQPGUZhAYTBsr74cDdSJWBxfk5f8FAW9WTvgJnRASbTbD8uvui6/jRp5ngDL01VVLuHd+qleTvvbuQKpxhMsuD+3ZtlJPM/fJxnYqAZDKXMCkVJjxNdYrQbbTbv4l0ERUgmr+/Q811AzQnM7wKKCK7Ij97hFh0QCz9YMSKaKIfK5VEHPHQSrzcbxiTCfjD/REP80juwqHbxDtT+tkGV8mZ01rNP2S4vvT+ix471UYNSnEvRiKHec1UnN6ipewC9Z1FxcsyOAjUzWg9ynfd8WI6zYpcWsn4dkHNqrdoruBQMNTO+dCoecjlw2t+h7R4bJzydjJYkJSBJoiOs8RuILu9/WarJsMJhQW3l6BHXHPE84yqzIWC56AqP825mvVO/OQ2W+EaU+TNuxvOPw7CSTG4GzfvvgvAnkIZSCEaRkg6hYfpeTAO8Iv3lfWf+GnmbMdfHFJTLS7uDK9EaXG6cMCRLQ/ffndop/TgGC1Rf+mI+/bZqphZHznVHubAJLIE0uZQdVajT6MMbNsl8H1Prcj2y83qa7W31w8DRMo1O3OYwFr659VG44wDahvuvtWc7TNgISibtr8tdz7AxF4ylaQ1j0FDAYQ=
  bucket: userapi.io
  region: us-west-2
