language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: kVc4AgC6au2VMC5+V3gm2CTEf6CUaCzD/Sh3UqO9QQGy/12q6px6/JSuTRR9ue061Tqe6ZsMs8wGLhotOGUocVROeM+oLbBReKMiorL5Oj3XfjbVoefpLNdiEWqn5pq2RAJhopidPb45JstxRL3nEap1gjVWC1DHsZ5S0oButcTXv1RKGsjJVjBs0rseMOKEjX0qwhzckAd2PZ8da12jtSo5gILsYoIHJg48BTuRq5qeOC1NR+fcknokrkfI5tdGt1oQ3lT2LDH02UiWLtVkoGVkc0GPacCNtZTkkYGFcDanGeup7REU85iSEqb4kDhnb2BVd2rzlKuJVcvynjUGr/N/P5Wv3UIu710yONFsW+0CcIRPQ9e5+agrcPaeGwVY2GshEt+qhr3eKhm91l8uI7rLRj7xInR1myrcAPTOhTurc0gqTG0j24r6L6rsBTyfuHiCFl+B9ejWfAGqlTPnLKCTLfzAnkWw6cJXkqx95b7BN/CYgl/SOulyzdbfQwLcrPq/rcUdLmxVpv9oD/4huwU4Prz4/B69zpec/TRbmT4na+7WdXdp9sMDt9vE1YQZgLwzPRr6+XrKdJUHbuHdcE3CmG5d+yf4aSftfCLE79EYpYenpYD43i7Z5QmpHsBlDmsGYQ7ZLGhGcXWmo61I91OGXdxheQBgDqUeNNO7B/Q=
script:
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: s3
  skip_cleanup: true
  local_dir: build
  access_key_id: AKIAI5P6VM2AE2HHNSTA
  secret_access_key:
    secure: EBuaXDMZn41+k7IQVbbIIlbQ9FHLaMgmp6Uw1KnEjg2sEqicaXND+QzmVAtlUpAMZEMKljNnmOqbXNZTlBWpFeCnXimCx44Pf1pvH5QRtf2Gc9eSv6HL0GQlgmkZ6TmrQiXULdG5rxnTHhNubfln+dwkyt4rkzaOq7UXpTFinlcGr9E+lfi15Ury1gAyJCEMHxUPpG38q+8lxU86CkrQ0he3gi4qv1D9Zl4d0yAsPPCt5RPI+kukJTTyA3K0tmziNFOG1QtV6IQ6x8iuc6CugFK0W9S/0Yrq7Q6Q9Fh1BwBe4L/nQKXIhiJOjRe8PHJfBozgq/1daCQpMR7FkMsQANKc/ur9iPE8AHQUT4jTL+e2mxTShAX6V6bjJlaV1bwFBe5WemM4cJIBfz30YBAzKEu0daJoqgdh7V5EI1auiSCd5BhPPOHMbfIejgom62Aj0eHvrTJOfcI3ELFkL0TidGz/cgq/5Wm3N3GrUNvzZIYZbonpS0FiLnGfFJ7AkvaB6dtSSUkE6B3m6BdwCksuogA04TPjtUz5QLlEJRUS7gSoi0Ory4XsQfugUDbB1iz3Ry/RsTeK7nnpX7373G958q8Xu6srndy8Ibo7vNITPloN0+BDmqeHHuaDZ+B55Pd2wRzWCj746wIFjZyrXWFI3dUCbzV906ciQQj6MrA200w=
  bucket: userapi.io
  region: us-west-2
