export const OPEN_WELCOME_MESSAGE = 'OPEN_WELCOME_MESSAGE'
export const CLOSE_WELCOME_MESSAGE = 'CLOSE_WELCOME_MESSAGE'

export const COPIED_CODE_SNIPPET = 'COPIED_CODE_SNIPPET'
export const CLOSE_COPIED_MESSAGE = 'CLOSE_COPIED_MESSAGE'
