export const API_HOST = 'https://api.userapi.io'

export const OPEN_WELCOME_MESSAGE = 'OPEN_WELCOME_MESSAGE'
export const CLOSE_WELCOME_MESSAGE = 'CLOSE_WELCOME_MESSAGE'

export const COPIED_CODE_SNIPPET = 'COPIED_CODE_SNIPPET'
export const CLOSE_COPIED_MESSAGE = 'CLOSE_COPIED_MESSAGE'
export const CHANGE_EXAMPLE_LANG = 'CHANGE_EXAMPLE_LANG'

export const README_REQUESTED = 'README_REQUESTED'
export const README_REQUEST_SUCCESS = 'README_REQUEST_SUCCESS'
export const README_REQUEST_FAILURE = 'README_REQUEST_FAILURE'
